/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.ChipGrade

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param errs 
 * @param freq 
 * @param grade 
 * @param hr 
 * @param id 
 * @param temp 
 * @param throttled 
 * @param volt 
 */


data class AntmChip (

    @Json(name = "errs")
    val errs: kotlin.Int,

    @Json(name = "freq")
    val freq: kotlin.Int,

    @Json(name = "grade")
    val grade: ChipGrade,

    @Json(name = "hr")
    val hr: kotlin.Float,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "temp")
    val temp: kotlin.Float,

    @Json(name = "throttled")
    val throttled: kotlin.Boolean,

    @Json(name = "volt")
    val volt: kotlin.Int

) {


}

