/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.AntmChainChipsStats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param chains 
 * @param chipsPerChain 
 */


data class AntmChainsChipsStats (

    @Json(name = "chains")
    val chains: kotlin.collections.List<AntmChainChipsStats>,

    @Json(name = "chips_per_chain")
    val chipsPerChain: kotlin.Int

) {


}

