/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.ChipGrade
import com.natio21.nocoiner_control.openapi.client.models.TempSensor

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param errors 
 * @param freq 
 * @param hashrate 
 * @param id 
 * @param status 
 * @param temp 
 * @param sensor 
 */


data class AntmiChipStats (

    @Json(name = "errors")
    val errors: kotlin.Int,

    @Json(name = "freq")
    val freq: kotlin.Int,

    @Json(name = "hashrate")
    val hashrate: kotlin.Float,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "status")
    val status: ChipGrade,

    @Json(name = "temp")
    val temp: kotlin.Float,

    @Json(name = "sensor")
    val sensor: TempSensor? = null

) {


}

