/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.TempSensorStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param board 
 * @param chip 
 * @param loc Location that refers to `chip.id`
 * @param state 
 */


data class AntmChipSensor (

    @Json(name = "board")
    val board: kotlin.Int,

    @Json(name = "chip")
    val chip: kotlin.Int,

    /* Location that refers to `chip.id` */
    @Json(name = "loc")
    val loc: kotlin.Int,

    @Json(name = "state")
    val state: TempSensorStatus

) {


}

