/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.AntmMinerStats

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param miner 
 */


@JsonClass(generateAdapter = true)
data class AuthCheckResponse(
    val status: String,
    val message: String
)


data class AuthCheck (

    @Json(name = "miner")
    val miner: AntmMinerStats
    //val miner: MinerSummary

) {


}

