/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param chips 
 * @param freq 
 * @param serial 
 */


data class AutotuneChain (

    @Json(name = "chips")
    val chips: kotlin.collections.List<kotlin.Int>,

    @Json(name = "freq")
    val freq: kotlin.Int,

    @Json(name = "serial")
    val serial: kotlin.String? = null

) {


}

