/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.AutotuneChain

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param chains 
 * @param freq 
 * @param hashrate 
 * @param modified 
 * @param volt 
 */


data class AutotuneResultsItem (

    @Json(name = "chains")
    val chains: kotlin.collections.List<AutotuneChain>,

    @Json(name = "freq")
    val freq: kotlin.Int,

    @Json(name = "hashrate")
    val hashrate: kotlin.Int,

    @Json(name = "modified")
    val modified: kotlin.Boolean,

    @Json(name = "volt")
    val volt: kotlin.Int

) {


}

