/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param grey 
 * @param orange 
 * @param red 
 */


data class ChainChipStatuses (

    @Json(name = "grey")
    val grey: kotlin.Int,

    @Json(name = "orange")
    val orange: kotlin.Int,

    @Json(name = "red")
    val red: kotlin.Int

) {


}

