/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param chips An array of per chip `freq` settings values. `0` (zero) value means that value used from `chain` settings
 * @param disabled Chain `disabled` settings value
 * @param freq Chain `freq` settings values. `0` (zero) value means that value used from `globals` settings
 */


data class ChainRaw (

    /* An array of per chip `freq` settings values. `0` (zero) value means that value used from `chain` settings */
    @Json(name = "chips")
    val chips: kotlin.collections.List<kotlin.Int>? = null,

    /* Chain `disabled` settings value */
    @Json(name = "disabled")
    val disabled: kotlin.Boolean? = null,

    /* Chain `freq` settings values. `0` (zero) value means that value used from `globals` settings */
    @Json(name = "freq")
    val freq: kotlin.Int? = null

) {


}

