/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.FactoryInfoChain

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param chains 
 * @param hasPics 
 * @param hrStock 
 * @param psuModel 
 * @param psuSerial 
 */


data class FactoryInfoReply (

    @Json(name = "chains")
    val chains: kotlin.collections.List<FactoryInfoChain>? = null,

    @Json(name = "has_pics")
    val hasPics: kotlin.Boolean? = null,

    @Json(name = "hr_stock")
    val hrStock: kotlin.Double? = null,

    @Json(name = "psu_model")
    val psuModel: kotlin.String? = null,

    @Json(name = "psu_serial")
    val psuSerial: kotlin.String? = null

) {


}

