/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.FanStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param maxRpm 
 * @param rpm 
 * @param status 
 */


data class Fan (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "max_rpm")
    val maxRpm: kotlin.Int,

    @Json(name = "rpm")
    val rpm: kotlin.Int,

    @Json(name = "status")
    val status: FanStatus

) {


}

