/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.HrMeasure
import com.natio21.nocoiner_control.openapi.client.models.InstallType
import com.natio21.nocoiner_control.openapi.client.models.Platform
import com.natio21.nocoiner_control.openapi.client.models.SystemInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param buildTime Build time
 * @param fwName Firmware name
 * @param fwVersion Firmware version
 * @param installType 
 * @param miner Pretty miner name
 * @param model Miner model code
 * @param platform 
 * @param hrMeasure 
 * @param serial 
 * @param buildName 
 * @param buildUuid 
 * @param system 
 */


data class InfoJson (

    /* Build time */
    @Json(name = "build_time")
    val buildTime: kotlin.String,

    /* Firmware name */
    @Json(name = "fw_name")
    val fwName: kotlin.String,

    /* Firmware version */
    @Json(name = "fw_version")
    val fwVersion: kotlin.String,

    @Json(name = "install_type")
    val installType: InstallType,

    /* Pretty miner name */
    @Json(name = "miner")
    val miner: kotlin.String,

    /* Miner model code */
    @Json(name = "model")
    val model: kotlin.String,

    @Json(name = "platform")
    val platform: Platform,

    @Json(name = "hr_measure")
    val hrMeasure: HrMeasure,

    @Json(name = "serial")
    val serial: kotlin.String,

    @Json(name = "build_name")
    val buildName: kotlin.String? = null,

    @Json(name = "build_uuid")
    val buildUuid: kotlin.String? = null,

    @Json(name = "system")
    val system: SystemInfo? = null

) {


}

