/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dhcp 
 * @param dnsservers 
 * @param gateway 
 * @param hostname 
 * @param ipaddress 
 * @param netmask 
 * @param enableNetworkCheck 
 */


data class InputNetworkConfFile (

    @Json(name = "dhcp")
    val dhcp: kotlin.Boolean,

    @Json(name = "dnsservers")
    val dnsservers: kotlin.collections.List<kotlin.String>,

    @Json(name = "gateway")
    val gateway: kotlin.String,

    @Json(name = "hostname")
    val hostname: kotlin.String,

    @Json(name = "ipaddress")
    val ipaddress: kotlin.String,

    @Json(name = "netmask")
    val netmask: kotlin.String,

    @Json(name = "enable_network_check")
    val enableNetworkCheck: kotlin.Boolean? = null

) {


}

