/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lg 
 * @param md 
 * @param sm 
 * @param xs 
 * @param xxs 
 */


data class Layout (

    @Json(name = "lg")
    val lg: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "md")
    val md: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "sm")
    val sm: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "xs")
    val xs: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "xxs")
    val xxs: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

