/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: mining,initializing,starting,autoMinusTuning,restarting,shuttingMinusDown,stopped,failure
 */

@JsonClass(generateAdapter = false)
enum class MinerState(val value: kotlin.String) {

    @Json(name = "mining")
    mining("mining"),

    @Json(name = "initializing")
    initializing("initializing"),

    @Json(name = "starting")
    starting("starting"),

    @Json(name = "auto-tuning")
    autoMinusTuning("auto-tuning"),

    @Json(name = "restarting")
    restarting("restarting"),

    @Json(name = "shutting-down")
    shuttingMinusDown("shutting-down"),

    @Json(name = "stopped")
    stopped("stopped"),

    @Json(name = "failure")
    failure("failure");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MinerState) "$data" else null

        /**
         * Returns a valid [MinerState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MinerState? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

