/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.CurrentPreset
import com.natio21.nocoiner_control.openapi.client.models.PresetSwitcherRaw

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param presetSwitcher 
 * @param currentPreset 
 */


data class PerfSummary (

    @Json(name = "preset_switcher")
    val presetSwitcher: PresetSwitcherRaw,

    @Json(name = "current_preset")
    val currentPreset: CurrentPreset? = null

) {


}

