/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param pass 
 * @param url 
 * @param user 
 */


data class Pool (

    @Json(name = "pass")
    val pass: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "user")
    val user: kotlin.String

) {


}

