/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * PresetSwitcher settings
 *
 * @param autochangeTopPreset 
 * @param checkTime 
 * @param decreaseTemp 
 * @param enabled 
 * @param ignoreFanSpeed 
 * @param riseTemp 
 * @param topPreset Profile name. Max profile that preset_switcher can switch
 */


data class PresetSwitcherRaw (

    @Json(name = "autochange_top_preset")
    val autochangeTopPreset: kotlin.Boolean? = null,

    @Json(name = "check_time")
    val checkTime: kotlin.Int? = null,

    @Json(name = "decrease_temp")
    val decreaseTemp: kotlin.Int? = null,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Json(name = "ignore_fan_speed")
    val ignoreFanSpeed: kotlin.Boolean? = null,

    @Json(name = "rise_temp")
    val riseTemp: kotlin.Int? = null,

    /* Profile name. Max profile that preset_switcher can switch */
    @Json(name = "top_preset")
    val topPreset: kotlin.String? = null

) {


}

