/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param after Number of seconds after the system will reboot By default, is 3 seconds
 */


data class RebootAfter (

    /* Number of seconds after the system will reboot By default, is 3 seconds */
    @Json(name = "after")
    val after: kotlin.Long

) {


}

