/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Apply config result
 *
 * @param rebootRequired Miner restart required to apply
 * @param restartRequired Miner restart required to apply config
 */


data class SaveConfigResult (

    /* Miner restart required to apply */
    @Json(name = "reboot_required")
    val rebootRequired: kotlin.Boolean,

    /* Miner restart required to apply config */
    @Json(name = "restart_required")
    val restartRequired: kotlin.Boolean

) {


}

