/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: `init`,ready,measure,error,unknown
 */

@JsonClass(generateAdapter = false)
enum class TempSensorStatus(val value: kotlin.String) {

    @Json(name = "init")
    `init`("init"),

    @Json(name = "ready")
    ready("ready"),

    @Json(name = "measure")
    measure("measure"),

    @Json(name = "error")
    error("error"),

    @Json(name = "unknown")
    unknown("unknown");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TempSensorStatus) "$data" else null

        /**
         * Returns a valid [TempSensorStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TempSensorStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

