/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.TempSensorStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param chipTemp 
 * @param pcbTemp 
 * @param status 
 */


data class TempSensor (

    @Json(name = "chip_temp")
    val chipTemp: kotlin.Int,

    @Json(name = "pcb_temp")
    val pcbTemp: kotlin.Int,

    @Json(name = "status")
    val status: TempSensorStatus

) {


}

