/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token 
 */

@JsonClass(generateAdapter = true)
data class UnlockRequest(
    val pw: String
)

@JsonClass(generateAdapter = true)
data class UnlockResponse(
    @Json(name = "token")
    val token: kotlin.String
)

data class UnlockSuccess (

    @Json(name = "token")
    val token: kotlin.String

) {


}

