/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.natio21.nocoiner_control.openapi.client.models

import com.natio21.nocoiner_control.openapi.client.models.Layout
import com.natio21.nocoiner_control.openapi.client.models.MinerConfigRaw
import com.natio21.nocoiner_control.openapi.client.models.NetworkConfFile
import com.natio21.nocoiner_control.openapi.client.models.PasswordChange
import com.natio21.nocoiner_control.openapi.client.models.RegionalSettings
import com.natio21.nocoiner_control.openapi.client.models.UiSettings

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param miner 
 * @param network 
 * @param regional 
 * @param ui 
 * @param layout 
 * @param password 
 */


data class ViewConfig (

    @Json(name = "miner")
    val miner: MinerConfigRaw,

    @Json(name = "network")
    val network: NetworkConfFile,

    @Json(name = "regional")
    val regional: RegionalSettings,

    @Json(name = "ui")
    val ui: UiSettings,

    @Json(name = "layout")
    val layout: Layout? = null,

    @Json(name = "password")
    val password: PasswordChange? = null

) {


}

